---
deployment:
  tasks:
    - /bin/mkdir -p /home/himy9571/public_html
    - /bin/mkdir -p /home/himy9571/laravel
    - /bin/mkdir -p /home/himy9571/laravel/app
    - /bin/mkdir -p /home/himy9571/laravel/bootstrap
    - /bin/mkdir -p /home/himy9571/laravel/config
    - /bin/mkdir -p /home/himy9571/laravel/database
    - /bin/mkdir -p /home/himy9571/laravel/resources
    - /bin/mkdir -p /home/himy9571/laravel/routes
    - /bin/mkdir -p /home/himy9571/laravel/storage
    - /bin/mkdir -p /home/himy9571/laravel/vendor
    - /bin/mkdir -p /home/himy9571/public_html/api
    - /bin/cp -R frontend/dist/. /home/himy9571/public_html/
    - /bin/cp -R backend/app/. /home/himy9571/laravel/app/
    - /bin/cp -R backend/bootstrap/. /home/himy9571/laravel/bootstrap/
    - /bin/cp -R backend/config/. /home/himy9571/laravel/config/
    - /bin/cp -R backend/database/. /home/himy9571/laravel/database/
    - /bin/cp -R backend/resources/. /home/himy9571/laravel/resources/
    - /bin/cp -R backend/routes/. /home/himy9571/laravel/routes/
    - /bin/cp -R backend/storage/. /home/himy9571/laravel/storage/
    - /bin/cp -R backend/vendor/. /home/himy9571/laravel/vendor/
    - /bin/cp -R backend/public/. /home/himy9571/public_html/api/
    - /bin/cp backend/artisan /home/himy9571/laravel/
    - /bin/cp backend/composer.json /home/himy9571/laravel/
    - /bin/cp backend/composer.lock /home/himy9571/laravel/
